# NumPy - Numeric Python

### What is NumPy?
An easy way to create, navigate and manipulate arrays and matrices of data


### Why do I need to know this?
Technically you don't, it doesn't come up too much directly in Data Science however it is the underlying functionality powering pandas and data sciences in python

No need to memorize, just be familar with the concept, where to look at how to use

### Getting Started with NumPy

`pip install numpy`

`import numpy as np`

### Common Functions in NumPy

- Create an array (list) of a desired size

`np.arange(start, stop, step)`

- Long way to do this

`
[x for x in range(start, stop, step)]
`

- Linspace - Create an array of evenly spaced values

`np.linspace(0,10,5)`

`array([ 0. ,  2.5,  5. ,  7.5, 10. ])`


###### Random

Get a random integer or get a list of random numbers between 2 numbers

`np.random.randint(1,99,10)`

`array([62, 89, 18, 41,  6, 67, 83, 48, 98, 56])`

Create a random array, results will be between 0 and 1

`np.random.rand(3)`

`array([0.37556892, 0.88167555, 0.21885929])`

Create a random Multi-Dimensional array, results will be between 0 and 1

`np.random.rand(3,3)`

`array([[0.43373283, 0.81953016, 0.60483176],
       [0.46460322, 0.04923629, 0.53102037],
       [0.34119516, 0.78186692, 0.88462712]])`


###### Re Shape a 1-dimensional array to a multi-dimensional array

Multi-dimensional array needs to match the number of items in the 1-dimensional array

`arr = np.arange(24)`

`arr.reshape(4,6)`

`array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])`
       
###### Max and Min

Get Min and Max values

`arr.min()` `arr.min()`

Get Min and Max index locations

`arr.argmin()` `arr.argmin()`


###### shape

Get the shape or the dimensions of the array, Row x Column

`arr.shape`


###### Indexing

Similar to lists and string for 1-dimensional arrays

`arr[0:3]` or `arr[:-2]`

For 2-dimensional Arrays, Single Bracket with comma (will see this with pandas

`arr[row, col]`

`arr[1:3,3:5]`

###### Comparison Operations

Selecting only values that match a certain condition (will see this with pandas data selection)

`arr > 5` or `arr[arr > 5]`

###### Math

We can use standard arithmetic values

`arr *,/,+,-,** 5`

Division by 0 -> Numpy will continue to run but will return either an **nan** or **inf**

nan -> 0 / 0
inf -> number / 0

For more, there is a list of Universal Math functions that can be run in NumPy


In [24]:
arr = np.arange(24)

arr = arr.reshape(4,6)

In [29]:
arr

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

In [34]:
arr[1:3,3:5]

array([[ 9, 10],
       [15, 16]])

In [43]:
arr * 5

array([[  0,   5,  10,  15,  20,  25],
       [ 30,  35,  40,  45,  50,  55],
       [ 60,  65,  70,  75,  80,  85],
       [ 90,  95, 100, 105, 110, 115]])

In [44]:
arr/arr

/var/folders/l_/qm4dplj969j0tcpycqgttbwc0000gn/T/ipykernel_74279/1862401812.py:1: RuntimeWarning: invalid value encountered in true_divide
  arr/arr


array([[nan,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.]])

In [45]:
1/arr

/var/folders/l_/qm4dplj969j0tcpycqgttbwc0000gn/T/ipykernel_74279/255282349.py:1: RuntimeWarning: divide by zero encountered in true_divide
  1/arr


array([[       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
        0.2       ],
       [0.16666667, 0.14285714, 0.125     , 0.11111111, 0.1       ,
        0.09090909],
       [0.08333333, 0.07692308, 0.07142857, 0.06666667, 0.0625    ,
        0.05882353],
       [0.05555556, 0.05263158, 0.05      , 0.04761905, 0.04545455,
        0.04347826]])