# NumPy Exercises

In [44]:
# Import Numpy

import numpy as np

# Type your code above this line

In [47]:
# Create 2 arrays
# 'a' will be a 1-dimensional array going from 0 to 20 printing every other value
# 'b' will be a 1-dimensional array going from 30 to 50 printing every other value


a = np.arange(0,20,2)
b = np.arange(30,50,2)
a, b

# Type your code above this line

# array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])
# array([30, 32, 34, 36, 38, 40, 42, 44, 46, 48])

(array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18]),
 array([30, 32, 34, 36, 38, 40, 42, 44, 46, 48]))

In [51]:
# Add 'a' and 'b' together
# Divide 'a' by 0
# Multiply 'b' by 50

print(a + b)
print(a / 0)
print(b * 50)




# Type your code above this line

# array([30, 34, 38, 42, 46, 50, 54, 58, 62, 66])
# array([nan, inf, inf, inf, inf, inf, inf, inf, inf, inf])
# array([1500, 1600, 1700, 1800, 1900, 2000, 2100, 2200, 2300, 2400])

[30 34 38 42 46 50 54 58 62 66]
[nan inf inf inf inf inf inf inf inf inf]
[1500 1600 1700 1800 1900 2000 2100 2200 2300 2400]


/var/folders/l_/qm4dplj969j0tcpycqgttbwc0000gn/T/ipykernel_78028/3406623875.py:6: RuntimeWarning: divide by zero encountered in true_divide
  print(a / 0)
/var/folders/l_/qm4dplj969j0tcpycqgttbwc0000gn/T/ipykernel_78028/3406623875.py:6: RuntimeWarning: invalid value encountered in true_divide
  print(a / 0)


In [97]:
# Create an array with 24 randomly selected values between -99 and 99
# Convert this into a 3x8 Matrix

# arr = np.random.randint(-99,99, 24)
# arr = arr.reshape(3,8)

arr = np.random.randint(-99,99, 24).reshape(3,8)


arr.shape




# Type your code above this line

# Values don't have to match
# array([[ 21,  80,  56,  26,  74,  -6, -42,  51],
#        [ 80,  94, -52, -55, -17, -13, -50, -12],
#        [-55, -43, -13,  15,  22,  28,  -4, -87]])


(3, 8)

In [114]:
# Find location of the min and max values from the Matrix

print(arr)
print('Min',arr.min())
print('Max',arr.max())

arr.argmin()
arr.argmax()

print('Min Location', np.unravel_index(arr.argmin(), arr.shape))
print('Max Location', np.unravel_index(arr.argmax(), arr.shape))


print('Min Value', arr[np.unravel_index(arr.argmin(), arr.shape)])
print('Max Value', arr[np.unravel_index(arr.argmax(), arr.shape)])

# Type your code above this line

# Values don't have to match
# (1, 5)
# (0, 4)

[[-52 -43  63  82  -3 -65 -99  19]
 [-83 -41  70 -67 -77  -5  92  19]
 [ 56 -77  84  97  89 -13 -10  82]]
Min -99
Max 97
Min Location (0, 6)
Max Location (2, 3)
Min Value -99
Max Value 97


In [121]:
# Create an array fro -10 to 10 with 32 values
# Reshape the array to an 8x4 array
# Change the values greater than 0 to be 1
# Change the values less than 0 to be -1


arr = np.random.randint(-10,10,32).reshape(8,4)
arr[arr > 0] = 1
arr[arr < 0] = -1
arr



# Type your code above this line

# Values don't have to match
# array([[-1,  1,  1, -1],
#        [ 1, -1,  1,  1],
#        [-1,  1,  1,  1],
#        [ 0, -1, -1,  1],
#        [ 1, -1, -1,  0],
#        [-1, -1,  1,  1],
#        [-1,  1,  1,  1],
#        [-1,  1,  1,  1]])

array([[ 1,  0,  1,  1],
       [ 1, -1, -1, -1],
       [-1, -1, -1,  1],
       [-1, -1,  1, -1],
       [ 1, -1, -1, -1],
       [-1, -1,  1, -1],
       [-1,  1, -1, -1],
       [-1, -1,  1, -1]])